version: "3.9"

services:
 postgres:
  container_name: db_hiper_wp
  image: postgres
  restart: always
  environment:
   POSTGRES_DB: integration
   POSTGRES_USER: user
   POSTGRES_PASSWORD: pass
  volumes:
    - ./postgres-data:/var/lib/postgresql/data
  ports:
    - 5432:5432
  network_mode: host
 web:
  container_name: webservice_hiper_wp
  build: ./hiper-wordpress/
  environment:
   PORT: 5000
   POSTGRES_HOST: localhost:5432
   POSTGRES_DB: integration
   POSTGRES_USER: user
   POSTGRES_PASSWORD: pass
   ADMIN_USER: kleyber
   ADMIN_PASS: UqFta9rE
  ports:
    - 5000:5000
  depends_on:
    - postgres
  network_mode: host
 
 sync_job:
  container_name: job_sync_hiper_wp
  build: ./hiper-wordpress-sync/
  environment:
   PORT: 5001
   POSTGRES_HOST: localhost:5432
   POSTGRES_DB: integration
   POSTGRES_USER: user
   POSTGRES_PASSWORD: pass
  ports:
    - 5001:5001
  depends_on:
    - postgres
  network_mode: host
 
  